config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#one'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav>
<ul>
<li><%= link_to 'one', pages_one_path %></li>
<li><%= link_to 'two', pages_two_path %></li>
<li><%= link_to 'three', pages_three_path %></li>
</ul>

</nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>proyecto first App </h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h2> lorem</h2>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente aliquid sunt provident esse praesentium assumenda, aut sequi aspernatur quam? Omnis perspiciatis non nam illo, porro aliquid harum officia laboriosam nobis!</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>
<%= image_tag 'imagen1.jpg'%>